export const categoryConstants = {
  GET_CATEGORY_REQUEST: "GET_CATEGORY_REQUEST",
  GET_CATEGORY_SUCCESS: "GET_CATEGORY_SUCCESS",
  GET_CATEGORY_ERROR: "GET_CATEGORY_ERROR",

  SAVE_CATEGORY_REQUEST: "SAVE_CATEGORY_REQUEST",
  SAVE_CATEGORY_SUCCESS: "SAVE_CATEGORY_SUCCESS",
  SAVE_CATEGORY_ERROR: "SAVE_CATEGORY_ERROR",

  UPDATE_CATEGORY_REQUEST: "UPDATE_CATEGORY_REQUEST",
  UPDATE_CATEGORY_SUCCESS: "UPDATE_CATEGORY_SUCCESS",
  UPDATE_CATEGORY_ERROR: "UPDATE_CATEGORY_ERROR",
};
