

export const productConstants = {
      GET_PRODUCT_REQUEST : 'GET_PRODUCT_REQUEST',
      GET_PRODUCT_SUCCESS : 'GET_PRODUCT_SUCCESS',
      GET_PRODUCT_ERROR : 'GET_PRODUCT_ERROR',
      GET_PRICE_REQUEST : 'GET_PRICE_REQUEST',
      GET_PRICE_SUCCESS : 'GET_PRICE_SUCCESS',
      GET_PRICE_ERROR : 'GET_PRICE_ERROR',

      GET_BILL_REQUEST : 'GET_BILL_REQUEST',
      GET_BILL_SUCCESS : 'GET_BILL_SUCCESS',
      GET_BILL_ERROR : 'GET_BILL_ERROR',

      GET_BILL_TODAY_REQUEST : 'GET_BILL_TODAY_REQUEST',
      GET_BILL_TODAY_SUCCESS : 'GET_BILL_TODAY_SUCCESS',
      GET_BILL_TODAY_ERROR : 'GET_BILL_TODAY_ERROR',

      SAVE_BILL_REQUEST : 'SAVE_BILL_REQUEST',
      SAVE_BILL_SUCCESS : 'SAVE_BILL_SUCCESS',
      SAVE_BILL_ERROR : 'SAVE_BILL_ERROR',

      SAVE_PRODUCT_REQUEST : 'SAVE_PRODUCT_REQUEST',
      SAVE_PRODUCT_SUCCESS : 'SAVE_PRODUCT_SUCCESS',
      SAVE_PRODUCT_ERROR : 'SAVE_PRODUCT_ERROR',
      UPDATE_PRODUCT_REQUEST : 'UPDATE_PRODUCT_REQUEST',
      UPDATE_PRODUCT_SUCCESS : 'UPDATE_PRODUCT_SUCCESS',
      UPDATE_PRODUCT_ERROR : 'UPDATE_PRODUCT_ERROR',


      SAVE_PRODUCT_LIST : 'SAVE_PRODUCT_LIST'
};